import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
            },
            colors: {
                // ── Palette Burkina Faso : Rouge / Noir / Jaune / Blanc ──
                'primary':                    '#b70100',
                'on-primary':                 '#ffffff',
                'primary-container':          '#e60000',
                'on-primary-container':       '#ffcdc7',
                'primary-fixed':              '#ffdad6',
                'primary-fixed-dim':          '#ffb4ab',
                'on-primary-fixed':           '#410002',
                'on-primary-fixed-variant':   '#b70100',
                'secondary':                  '#fcd400',
                'on-secondary':               '#1a1c1c',
                'secondary-container':        '#fff3b3',
                'on-secondary-container':     '#5c4d00',
                'secondary-fixed':            '#fff8d6',
                'secondary-fixed-dim':        '#f5e6b3',
                'on-secondary-fixed':         '#2e2600',
                'on-secondary-fixed-variant': '#5c4d00',
                'tertiary':                   '#b70100',
                'on-tertiary':                '#ffffff',
                'tertiary-container':         '#e60000',
                'on-tertiary-container':      '#ffffff',
                'tertiary-fixed':             '#ffdad6',
                'tertiary-fixed-dim':         '#ffb4ab',
                'on-tertiary-fixed':          '#410002',
                'on-tertiary-fixed-variant':  '#b70100',
                'error':                      '#ba1a1a',
                'on-error':                   '#ffffff',
                'error-container':            '#ffdad6',
                'on-error-container':         '#93000a',
                'background':                 '#ffffff',
                'on-background':              '#1a1c1c',
                'surface':                    '#ffffff',
                'on-surface':                 '#1a1c1c',
                'surface-variant':            '#f3f3f3',
                'on-surface-variant':         '#6b6b6b',
                'surface-container-lowest':   '#ffffff',
                'surface-container-low':      '#f9f9f9',
                'surface-container':          '#f3f3f3',
                'surface-container-high':     '#eeeeee',
                'surface-container-highest':  '#e8e8e8',
                'surface-bright':             '#ffffff',
                'surface-dim':                '#e8e8e8',
                'surface-tint':               '#b70100',
                'outline':                    '#d9d9d9',
                'outline-variant':            '#eeeeee',
                'inverse-surface':            '#1a1c1c',
                'inverse-on-surface':         '#ffffff',
                'inverse-primary':            '#ffb4ab',

                // ── Aliases Rouge / Jaune / Noir / Blanc ─────────────
                'kinetic': {
                    red:         '#b70100',
                    'red-hover': '#9a0100',
                    'red-light': '#ffdad6',
                    gold:        '#fcd400',
                    'gold-light':'#fff8d6',
                },
                status: {
                    'green-bg':   '#f0fdf4',
                    'green-text': '#166534',
                    'green-ring': '#86efac',
                    'yellow-bg':  '#fefce8',
                    'yellow-text':'#854d0e',
                    'yellow-ring':'#fde68a',
                    'red-bg':     '#fef2f2',
                    'red-text':   '#991b1b',
                    'red-ring':   '#fecaca',
                    'blue-bg':    '#eff6ff',
                    'blue-text':  '#1e40af',
                    'blue-ring':  '#bfdbfe',
                    'slate-bg':   '#f8fafc',
                    'slate-text': '#475569',
                    'slate-ring': '#cbd5e1',
                },

                // ── Back-office dark theme ────────────────────────────
                'admin': {
                    'bg':     '#0f172a',
                    'card':   '#1e293b',
                    'border': '#334155',
                    'text':   '#e2e8f0',
                    'muted':  '#64748b',
                },
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                md:      '0.375rem',
                lg:      '0.5rem',
                xl:      '0.75rem',
                '2xl':   '1rem',
                '3xl':   '1.5rem',
                full:    '9999px',
            },
            boxShadow: {
                sm:    '0 1px 3px rgba(0,0,0,0.06)',
                md:    '0 4px 12px rgba(0,0,0,0.08)',
                lg:    '0 8px 24px rgba(0,0,0,0.10)',
                xl:    '0 16px 48px rgba(0,0,0,0.12)',
                card:  '0 1px 4px rgba(0,0,0,0.06)',
                'ambient':    '0 12px 32px rgba(183,1,0,0.08)',
                'red-glow':    '0 4px 14px rgba(183,1,0,0.25)',
                'primary-glow':'0 4px 20px rgba(183,1,0,0.25)',
            },
        },
    },
    plugins: [forms],
};
